In [ ]:
# Import Important Libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time 
all_books = []

In [48]:
# 1.loops from 1 to 50 (web scraping)
for page_num in range(1, 51):
    # Dynamic URL that will change the page number every loop
    url = f"http://books.toscrape.com/catalogue/page-{page_num}.html"

    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    books = soup.find_all('article', class_='product_pod')

    # Extracting data from all the books on the page
    for book in books:
        title = book.h3.a['title']
        price = book.find('p', class_='price_color').text
        rating = book.find('p', class_='star-rating')['class'][1]

        all_books.append([title, price, rating])

    print(f"Page {page_num} successfully scraped!")
    time.sleep(0.1)

Page 1 successfully scraped!
Page 2 successfully scraped!
Page 3 successfully scraped!
Page 4 successfully scraped!
Page 5 successfully scraped!
Page 6 successfully scraped!
Page 7 successfully scraped!
Page 8 successfully scraped!
Page 9 successfully scraped!
Page 10 successfully scraped!
Page 11 successfully scraped!
Page 12 successfully scraped!
Page 13 successfully scraped!
Page 14 successfully scraped!
Page 15 successfully scraped!
Page 16 successfully scraped!
Page 17 successfully scraped!
Page 18 successfully scraped!
Page 19 successfully scraped!
Page 20 successfully scraped!
Page 21 successfully scraped!
Page 22 successfully scraped!
Page 23 successfully scraped!
Page 24 successfully scraped!
Page 25 successfully scraped!
Page 26 successfully scraped!
Page 27 successfully scraped!
Page 28 successfully scraped!
Page 29 successfully scraped!
Page 30 successfully scraped!
Page 31 successfully scraped!
Page 32 successfully scraped!
Page 33 successfully scraped!
Page 34 successfully scraped!
Page 35 successfully scraped!
Page 36 successfully scraped!
Page 37 successfully scraped!
Page 38 successfully scraped!
Page 39 successfully scraped!
Page 40 successfully scraped!
Page 41 successfully scraped!
Page 42 successfully scraped!
Page 43 successfully scraped!
Page 44 successfully scraped!
Page 45 successfully scraped!
Page 46 successfully scraped!
Page 47 successfully scraped!
Page 48 successfully scraped!
Page 49 successfully scraped!
Page 50 successfully scraped!

In [49]:
# 2. Converting data into dataframe
df_large = pd.DataFrame(all_books, columns=['Product_Name', 'Price', 'Rating'])

print("\n--- Scraping Completed! ---")
print("Total Rows and Columns:", df_large.shape)

--- Scraping Completed! ---
Total Rows and Columns: (1000, 3)

In [50]:
df_large.shape

(1000, 3)

In [51]:
df_large.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_Name  1000 non-null   object
 1   Price         1000 non-null   object
 2   Rating        1000 non-null   object
dtypes: object(3)
memory usage: 23.6+ KB

In [52]:
df_large.isnull().sum()
#if null then - df_clean_row = df_large['price'].fillna(median))

Product_Name    0
Price           0
Rating          0
dtype: int64

In [53]:
# 1. Removing currency symbol from df_large price column and converting into float
df_large['Price_Cleaned'] = df_large['Price'].str[1:].astype(float)

In [54]:
# 2. converting rating from text to number
rating_map = {
    'One': 1,
    'Two': 2,
    'Three': 3,
    'Four': 4,
    'Five': 5
}

In [55]:
# 3. Converting df_large rating to numeric using map function
df_large['Rating_Numeric'] = df_large['Rating'].map(rating_map)

In [56]:
# 4. creating a clean dataset by dropping old, dirty column
df_clean_ecommerce = df_large.drop(columns=['Price', 'Rating'])

print("--- 1,000 Rows Cleaned Data Ka View ---")
print(df_clean_ecommerce.head())

--- 1,000 Rows Cleaned Data Ka View ---
                            Product_Name  Price_Cleaned  Rating_Numeric
0                   A Light in the Attic          51.77               3
1                     Tipping the Velvet          53.74               1
2                             Soumission          50.10               1
3                          Sharp Objects          47.82               4
4  Sapiens: A Brief History of Humankind          54.23               5

In [57]:
# save the clean data to a new file
df_clean_ecommerce.to_csv("cleaned_ecommerce_1000.csv", index=False)

In [58]:
# creating order data
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [59]:
# 1. give unique identity
df_clean_ecommerce['Product_ID'] = [f"PROD{1000 + i}" for i in range(len(df_clean_ecommerce))]

In [60]:
# 2. Setup (for number of order)
num_orders = 1000
order_list = []

# list of product id
all_product_ids = df_clean_ecommerce['Product_ID'].values

In [61]:
# 3. Simple Loop (row creation)
for i in range(num_orders):
    order_id = f"ORD{50000 + i}"       # ORD50000, ORD50001, ORD50002...
    customer_id = f"CUST{100 + (i % 50)}"
    prod_id = np.random.choice(all_product_ids)
    quantity = np.random.randint(1, 4)

    # put all order in list
    order_list.append([order_id, customer_id, prod_id, quantity])

In [62]:
# 4. DataFrame creation
df_orders = pd.DataFrame(order_list, columns=['OrderID', 'CustomerID', 'Product_ID', 'Quantity'])

print("--- order table is ready! ---")
print(df_orders.head())

--- order table is ready! ---
    OrderID CustomerID Product_ID  Quantity
0  ORD50000    CUST100   PROD1554         2
1  ORD50001    CUST101   PROD1042         2
2  ORD50002    CUST102   PROD1437         1
3  ORD50003    CUST103   PROD1930         1
4  ORD50004    CUST104   PROD1750         3

In [63]:
df_orders.shape

(1000, 4)

In [64]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     1000 non-null   object
 1   CustomerID  1000 non-null   object
 2   Product_ID  1000 non-null   object
 3   Quantity    1000 non-null   int64
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [65]:
df_orders.isnull().sum()

OrderID       0
CustomerID    0
Product_ID    0
Quantity      0
dtype: int64

In [66]:
df_orders.head()

    OrderID CustomerID Product_ID  Quantity
0  ORD50000    CUST100   PROD1554         2
1  ORD50001    CUST101   PROD1042         2
2  ORD50002    CUST102   PROD1437         1
3  ORD50003    CUST103   PROD1930         1
4  ORD50004    CUST104   PROD1750         3

In [67]:
# 1. Check in dim_products  Product_ID is unique or not
duplicate_products = df_clean_ecommerce['Product_ID'].duplicated().sum()
print(f"Products Table me Duplicate IDs: {duplicate_products}")
# output should be zero!

# 2. Check if all Product_IDs in the fact order are accessed in the product table
missing_links = ~df_orders['Product_ID'].isin(df_clean_ecommerce['Product_ID'])
print(f"Orders Table me missing Product links: {missing_links.sum()}")
# output should be zero!

Products Table me Duplicate IDs: 0
Orders Table me missing Product links: 0